### ISSUE TITLE
TipsCalculator - Review my app

### ISSUE THREAD

**Issue by julia** [julia/tips#1]
My app is complete, please review. /cc @codepathreview

**Comment by timothy1ee** [comment]
Good work. This prework is a preview of our weekly project process. Generally, weekly projects take between 5-10 hours to complete the required features and an additional 5-10 hours to complete the optional features. In general, we've seen that the more hours you log, the quicker you improve your proficiency with iOS.

Unfortunately, the class is now full, but you can re-use this project for submitting to a future class. The next class starts May 18th. You should use the extra time to add more customizations like styling and animations, we take any improvements you make into consideration when we're reviewing your application.

In the meantime, you're welcome to follow along with the course remotely. If you like, I can add you as a course observer. As a course observer, you have access to the recorded class lecture, the course materials, and you can follow along with the weekly projects.

**Comment by julia** [comment]
@timothy1ee Yes, I'd like to be added as course observer.
